export default store = [
  {
    id: 1,
    image: require('../app/src/imag/back1.png'),
    image2: require('../app/src/imag/Zara.png'),
    des: 'Store Number 1',
    date: 'Last updated: 8/7/2022',
    icon: 'down',
    currency: '$',
    price: '200',
  },
  {
    id: 2,
    image: require('../app/src/imag/back2.png'),
    image2: require('../app/src/imag/b2.png'),
    des: 'Store Number 1',
    date: 'Last updated: 8/7/2022',
    icon: 'down',
    currency: '$',
    price: '150',
  },
  {
    id: 3,
    image: require('../app/src/imag/back3.png'),
    image2: require('../app/src/imag/b3.png'),
    des: 'Store Number 1',
    date: 'Last updated: 8/7/2022',
    icon: 'down',
    currency: '$',
    price: '50',
  },

  {
    id: 4,
    image: require('../app/src/imag/b5.png'),
    des: 'Store Number 1',
    date: 'Last updated: 8/7/2022',
    icon: 'down',
    currency: '$',
    price: '50',
  },
];
